# volumes:
#     postgres-data:
#         external: true
#     pg-admin:
#         external: true
services:
#     postgres:
#         image: postgres:14.5-bullseye
#         volumes:
#             - postgres-data:/var/lib/postgresql/data
#         environment:
#             POSTGRES_PASSWORD: secret
#             POSTGRES_USER: user
#             POSTGRES_DB: prestigepalate
#         ports:
#             - 15432:5432
#     pg-admin:
#         image: dpage/pgadmin4
#         volumes:
#             - pg-admin:/var/lib/pgadmin
#         ports:
#             - 8082:80
#         environment:
#             PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#             PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#             PGADMIN_DISABLE_POSTFIX: 1
    fastapi:
        environment:
            # WAIT_HOSTS: postgres:5432
            CORS_HOST: http://localhost:5173
            # DATABASE_URL: mysqlnd://user:cpses_fuuul8r6iz@localhost/portfolio
        build:
            context: backend
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
    frontend:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"
        environment:
            VITE_APP_API_HOST: ${VITE_APP_API_HOST}
            VITE_PUBLIC_URL: http://localhost:5173/
            HOST: 0.0.0.0
            NODE_ENV: development
