volumes:
    mariadb:
    phpmyadmin:
services:
    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSL_DATABASE: portfolio
        volumes:
            - mariadb:/var/lib/mysql
            - ./dev/docker_mysql_init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        ports:
            - 8080:80
    fastapi:
        restart: always
        environment:
            WAIT_HOSTS: db:3306
            CORS_HOST: http://localhost:5173
            DATABASE_URL: mysql://${DB_USERNAME}:${DB_PASSWORD}@mariadb:${DB_PORT}/${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        build:
            context: backend
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
    frontend:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"
        environment:
            VITE_APP_API_HOST: ${VITE_APP_API_HOST}
            VITE_PUBLIC_URL: http://localhost:5173/
            HOST: 0.0.0.0
            NODE_ENV: development
