services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    fastapi:
        environment:
            WAIT_HOSTS: db:3306
            CORS_HOST: http://localhost:5173
            DB_HOST: 72.167.205.111
            DB_PORT: 3306
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        build:
            context: backend
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
    frontend:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"
        environment:
            VITE_APP_API_HOST: ${VITE_APP_API_HOST}
            VITE_PUBLIC_URL: http://localhost:5173/
            HOST: 0.0.0.0
            NODE_ENV: development
